import type { Metadata } from 'next'
import { Dosis } from 'next/font/google'
import './globals.css'
import type { AppTheme } from '@/types'
import { cookies } from 'next/headers'
import { Header } from '@/components/layout/header'
import { HoleBackground } from '@/components/animate-ui/components/backgrounds/hole'
import { Toaster } from '@/components/ui/sonner'

const dosis = Dosis({
  variable: '--font-dosis',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const themeCookieStore = (await cookies()).get('theme')?.value
  const theme =
    themeCookieStore && ['light', 'dark'].includes(themeCookieStore)
      ? (themeCookieStore as AppTheme)
      : 'dark'
  return (
    <html className={theme} lang="zh-CN">
      <body className={`${dosis.variable} max-w-screen overflow-x-hidden antialiased`}>
        <Header theme={theme} />
        <HoleBackground className="fixed top-0 left-0 z-[-1] h-full w-full" />
        {children}
        <Toaster theme={theme} />
      </body>
    </html>
  )
}
