import type { Metadata } from 'next'
import { Dosis } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/layout/header'
import { HoleBackground } from '@/components/animate-ui/components/backgrounds/hole'
import { Toaster } from '@/components/ui/sonner'
import { getSidebarExpand, getTheme } from '@/lib/cookies'

const dosis = Dosis({
  variable: '--font-dosis',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const theme = await getTheme()
  const sidebarExpand = await getSidebarExpand()
  return (
    <html className={`${theme} scroll-smooth`} lang="zh-CN">
      <body
        className={`${dosis.variable} max-w-screen overflow-x-hidden antialiased ${sidebarExpand && 'sidebar-expand'}`}
      >
        <HoleBackground className="fixed top-0 left-0 z-[-1] h-full w-full" />
        <Header theme={theme} />
        {children}
        <Toaster theme={theme} />
      </body>
    </html>
  )
}
