import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import type { AppTheme } from '@/types'
import { cookies } from 'next/headers'
import { Header } from '@/components/header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const themeCookieStore = (await cookies()).get('theme')?.value
  const theme =
    themeCookieStore && ['light', 'dark'].includes(themeCookieStore)
      ? (themeCookieStore as AppTheme)
      : 'light'
  console.log('渲染触发')
  return (
    <html className={theme} lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} max-w-screen overflow-x-hidden antialiased`}
      >
        <Header theme={theme} />
        {children}
      </body>
    </html>
  )
}
