packages:
  - apps/*
  - packages/*

catalog:
  '@commitlint/cli': latest
  '@commitlint/config-conventional': latest
  '@radix-ui/react-slot': latest
  '@radix-ui/react-tabs': latest
  '@tabler/icons-react': latest
  '@tailwindcss/postcss': ^4
  '@types/jest': latest
  '@types/node': ^20
  '@types/react': ^19
  '@types/react-dom': ^19
  typescript: ^5
  ts-jest: latest
  ts-node: latest
  turbo: latest
  husky: latest
  jest: latest
  czg: latest
  lint-staged: latest
  prettier: latest
  prettier-plugin-tailwindcss: latest
  class-variance-authority: ^0
  clsx: ^2
  embla-carousel-autoplay: ^8
  embla-carousel-react: ^8
  eslint: ^9
  eslint-config-next: ^16
  eslint-config-prettier: ^10
  lucide-react: ^0
  motion: latest
  next: ^16
  react: ^19
  react-dom: ^19
  sonner: latest
  tailwind-merge: ^3
  tailwindcss: ^4
  tw-animate-css: ^1
  zustand: latest
